# Balanced test - all categories with best performing models

models:
  # Best free model
  - id: "mistralai/mistral-7b-instruct:free"
    name: "Mistral-7B-Free"
    type: "small"
    cost_per_1k: 0.0
    
  # Best ultra-budget models
  - id: "mistralai/ministral-3b"
    name: "Ministral-3B"
    type: "tiny"
    cost_per_1k: 0.00002
    
  - id: "mistralai/ministral-8b"
    name: "Ministral-8B"
    type: "small"
    cost_per_1k: 0.00002
    
  # Best budget models
  - id: "deepseek/deepseek-chat"
    name: "DeepSeek-Chat"
    type: "large"
    cost_per_1k: 0.00014
    
  - id: "qwen/qwen-2.5-7b-instruct"
    name: "Qwen-2.5-7B"
    type: "small"
    cost_per_1k: 0.00018
    
  - id: "qwen/qwen-2.5-72b-instruct"
    name: "Qwen-2.5-72B"
    type: "large"
    cost_per_1k: 0.00018
    
  # Best performance models
  - id: "openai/gpt-3.5-turbo"
    name: "GPT-3.5-Turbo"
    type: "medium"
    cost_per_1k: 0.0005
    
  - id: "anthropic/claude-3-haiku"
    name: "Claude-3-Haiku"
    type: "small"
    cost_per_1k: 0.00025

sgr_modes:
  - name: "off"
    description: "No structured guidance"
    
  - name: "lite"
    description: "Minimal structure"
    schema_fields: ["task_understanding", "solution"]
    
  - name: "full"
    description: "Full structured reasoning"
    schema_fields: ["requirements_analysis", "approach", "implementation", "validation"]

# Test 2 tasks from each category
test_categories:
  code_generation:
    tasks: ["code_simple_001", "code_api_002"]
    
  rag_qa:
    tasks: ["rag_simple_001", "rag_conflict_003"]
    
  summarization:
    tasks: ["sum_report_001", "sum_technical_002"]
    
  planning_decision:
    tasks: ["plan_arch_001", "plan_product_007"]
    
  data_etl:
    tasks: ["data_clean_001", "data_transform_007"]
    
  agent_workflow:
    tasks: ["agent_code_001", "agent_rag_007"]

# Total: 12 tasks × 8 models × 3 modes = 288 API calls
# Estimated cost: ~$0.10

evaluation:
  runs_per_task: 1
  temperature: 0.1
  max_tokens: 2000
  timeout: 60

reporting:
  formats: ["markdown", "json", "csv"]
  include_cost_analysis: true
  highlight_free_models: true
  track_latency_percentiles: true
  generate_category_analysis: true
  generate_sgr_improvement_analysis: true