# YandexGPT Test Configuration
# Тестирование российских моделей YandexGPT

models:
  # YandexGPT Lite - легкая и быстрая модель
  - id: "yandexgpt-lite"
    name: "YandexGPT-Lite"
    type: "budget"
    cost_per_1k: 0.002  # ~0.2₽ за 1k токенов
    api_endpoint: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
    supports_json: true
    
  # YandexGPT Pro - полная версия
  - id: "yandexgpt"
    name: "YandexGPT-Pro"
    type: "mid"
    cost_per_1k: 0.02  # ~2₽ за 1k токенов
    api_endpoint: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
    supports_json: true
    
  # Для сравнения - другие бюджетные модели
  - id: "mistralai/mistral-7b-instruct:free"
    name: "Mistral-7B-Free"
    type: "free"
    cost_per_1k: 0.0
    
  - id: "deepseek/deepseek-chat"
    name: "DeepSeek-Chat"
    type: "budget"
    cost_per_1k: 0.00014

# SGR modes
sgr_modes:
  - name: "off"
    description: "Baseline without SGR"
    
  - name: "lite"
    description: "Lightweight SGR"
    schema_fields: ["task_understanding", "solution"]
    
  - name: "full"
    description: "Full SGR"
    schema_fields: ["requirements_analysis", "approach", "implementation", "validation"]

# Task categories - фокус на простых задачах для начала
categories:
  - name: "codegen"
    description: "Code generation tasks"
    
  - name: "summarization"
    description: "Text summarization"
    
  - name: "rag"
    description: "Question answering"

# Конкретные задачи для теста
tasks:
  # Простые задачи кодогенерации
  - "code_cli_converter_001"
  - "code_string_utils_002"
  
  # Суммаризация
  - "sum_report_001"
  - "sum_technical_doc_002"
  
  # RAG
  - "rag_factual_qa_001"
  
# Test settings
test_settings:
  max_retries: 2
  timeout: 30
  temperature: 0.6  # YandexGPT хорошо работает с низкой температурой
  max_tokens: 1000

# Evaluation
evaluation:
  metrics:
    - accuracy
    - completeness
    - coherence
    - response_time
  composite_scoring: true

# Reporting
reporting:
  formats:
    - json
    - markdown
  include_artifacts: true
  visualization: true

# Специфичные настройки для YandexGPT
yandex_settings:
  folder_id: "your-folder-id"  # Нужно указать ID каталога
  auth_type: "iam"  # или "api-key"
  model_uri: "gpt://your-folder-id/yandexgpt-lite/latest"