name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with ruff
        run: |
          pip install ruff==0.4.4
          ruff check --output-format=github .

      - name: Check formatting with black
        run: |
          pip install black==24.3.0
          black --check .

      - name: Static typing with mypy
        run: |
          mypy --strict src || true  # allow non-zero exit until typing coverage improved

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mcp-sgr:ci .